server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://rs-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: dispatcher-service
          uri: lb://rs-dispatcher
          predicates:
            - Path=/api/dispatcher/**
          filters:
            - StripPrefix=2
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
